"""
AI Threat Analyzer Module
Performs hybrid rule-based + NLP threat detection and classification.
Uses sklearn for ML classification, NLTK for text processing, and
regex-based pattern matching for rule-based detection.
"""
import json
import re
import os
import uuid
from datetime import datetime
from typing import List, Tuple, Dict, Any
from dotenv import load_dotenv

load_dotenv()

try:
    import spacy
    # Load the English NLP model (will fail gracefully if not installed yet)
    _nlp = spacy.load("en_core_web_sm")
except Exception:
    _nlp = None

try:
    from core import technique_classifier
except ImportError:
    technique_classifier = None

from models.schemas import (
    ATTACKTechnique, ThreatResult, RiskScore, SeverityLevel,
    ThreatEntity, MitigationStep
)
from core.llm_engine import LocalHuggingFaceEngine
from core.ml_engine import ml_engine
from core.framework_mapper import map_to_defend, map_to_nist, map_to_owasp
from core import technique_embedder

llama_rag = LocalHuggingFaceEngine()

# Load ATT&CK database at module level
_ATTACK_DB = None
_DEFEND_DB = None
_NIST_DB = None
_OWASP_DB = None

# Expanded ATT&CK keywords (auto-generated by scripts/train_real_data.py)
_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data')
_EXPANDED_KW_PATH = os.path.join(_DATA_DIR, 'attack_keywords.json')
_EXPANDED_KW: Dict[str, list] = {}

# Generic words that appear in normal text and cause false positives
_GENERIC_STOPWORDS = {
    'code', 'network', 'user', 'device', 'remote', 'data', 'system', 'file',
    'server', 'service', 'access', 'process', 'execution', 'information',
    'application', 'software', 'security', 'control', 'command', 'time',
    'host', 'port', 'client', 'protocol', 'connection', 'session',
    'value', 'name', 'path', 'key', 'type', 'response', 'request',
    'update', 'change', 'log', 'event', 'error', 'message', 'source',
    'target', 'object', 'group', 'list', 'table', 'record', 'account',
    'authentication', 'configuration', 'monitor', 'run', 'management'
}

def _load_expanded_keywords():
    """Load auto-generated ATT&CK keyword expansions and merge into THREAT_SIGNATURES.
    Filters out generic single-word keywords that cause false positives."""
    global _EXPANDED_KW
    if not os.path.exists(_EXPANDED_KW_PATH):
        return  # Not yet trained — silently skip
    try:
        with open(_EXPANDED_KW_PATH) as f:
            _EXPANDED_KW = json.load(f)
        # Merge expanded keywords into existing THREAT_SIGNATURES
        for category, kw_list in _EXPANDED_KW.items():
            if category in THREAT_SIGNATURES:
                existing = set(THREAT_SIGNATURES[category]['keywords'])
                # Only add multi-word phrases or specific single words (not generic ones)
                new_kws = []
                for k in kw_list:
                    if k in existing:
                        continue
                    # Filter out generic single-word keywords
                    if ' ' not in k and k.lower() in _GENERIC_STOPWORDS:
                        continue
                    # Skip very short words (3 chars or less) unless multi-word
                    if ' ' not in k and len(k) <= 3:
                        continue
                    new_kws.append(k)
                THREAT_SIGNATURES[category]['keywords'].extend(new_kws[:30])
            # else: new category — only add if it maps to a known one
        import logging
        logging.getLogger(__name__).info(
            f"Loaded ATT&CK expanded keywords: "
            f"{sum(len(v) for v in _EXPANDED_KW.values())} keywords across {len(_EXPANDED_KW)} categories"
        )
    except Exception as e:
        import logging
        logging.getLogger(__name__).warning(f"Could not load expanded ATT&CK keywords: {e}")



def _load_databases():
    global _ATTACK_DB, _DEFEND_DB, _NIST_DB, _OWASP_DB
    base = os.path.join(os.path.dirname(__file__), '..', 'data')
    with open(os.path.join(base, 'mitre_attack.json')) as f:
        _ATTACK_DB = json.load(f)
    with open(os.path.join(base, 'mitre_defend.json')) as f:
        _DEFEND_DB = json.load(f)
    with open(os.path.join(base, 'nist_controls.json')) as f:
        _NIST_DB = json.load(f)
    with open(os.path.join(base, 'owasp_data.json')) as f:
        _OWASP_DB = json.load(f)

_load_databases()

# NOTE: _load_expanded_keywords() is called AFTER THREAT_SIGNATURES is defined (see end of signatures block)

# Kick off technique embedding precomputation in a background thread so startup is non-blocking
import threading
_embed_thread = threading.Thread(target=technique_embedder.precompute_technique_embeddings, daemon=True)
_embed_thread.start()



# Threat classification keyword sets with weights
THREAT_SIGNATURES = {
    'web_attack': {
        'keywords': ['sql injection', 'xss', 'cross-site', 'csrf', 'ssrf', 'xxe', 
                     'path traversal', 'directory traversal', 'file inclusion', 
                     'remote file', 'http flood', 'web application', 'api abuse',
                     'buffer overflow', 'heap overflow', 'stack overflow',
                     'remote code execution', 'arbitrary code execution',
                     'code execution', 'command injection', 'code injection',
                     'use after free', 'use-after-free', 'memory corruption',
                     'integer overflow', 'format string', 'out of bounds'],
        'techniques': ['T1190', 'T1190.001', 'T1190.002', 'T1203'],
        'weight': 0.9
    },
    'credential_dumping': {
        'keywords': ['mimikatz', 'dump credentials', 'dumped credentials', 'credentials dump', 
                     'credential dump', 'lsass', 'sam database', 'hashdump', 'secretsdump'],
        'techniques': ['T1003'],
        'weight': 0.88
    },
    'credential_brute_force': {
        'keywords': ['brute force', 'password spray', 'credential stuffing', 'login attempt',
                     'authentication failure', 'invalid password', 'account lockout'],
        'techniques': ['T1110'],
        'weight': 0.87
    },
    'credential_pass_hash': {
        'keywords': ['pass the hash', 'pass-the-hash', 'pth', 'ntlm hash', 'hash used to authenticate'],
        'techniques': ['T1555'],
        'weight': 0.86
    },
    'credential_kerberos': {
        'keywords': ['kerberoasting', 'golden ticket', 'silver ticket', 'dcsync'],
        'techniques': ['T1558'],
        'weight': 0.89
    },
    'malware_ransomware': {
        'keywords': ['ransomware', 'ryuk', 'wannacry', 'darkside', 'petya', 'notpetya', 
                     'lockbit', 'blackcat', 'alphv', 'conti', 'revil', 'cryptolocker'],
        'techniques': ['T1486'],
        'weight': 0.95
    },
    'malware_backdoor_trojan': {
        'keywords': ['trojan', 'backdoor', 'rootkit', 'spyware', 'keylogger', 'botnet', 
                     'worm', 'virus', 'rat', 'payload', 'dropper', 'loader', 'cobalt strike', 
                     'metasploit', 'emotet', 'lazarus', 'apt28', 'apt29', 'webshell', 'web shell',
                     'macro payload', 'malicious document', 'mirai'],
        'techniques': ['T1059', 'T1055', 'T1027', 'T1566'],
        'weight': 0.9
    },
    'network_attack': {
        'keywords': ['port scan', 'network scan', 'nmap', 'reconnaissance', 'syn flood',
                     'ddos', 'dos attack', 'packet', 'sniff', 'arp poison', 'mitm',
                     'man in the middle', 'dns poison', 'spoofing'],
        'techniques': ['T1046', 'T1040', 'T1071', 'T1095'],
        'weight': 0.8
    },
    'data_exfiltration': {
        'keywords': ['data exfiltration', 'data theft', 'exfil', 'data breach', 'leak',
                     'stolen data', 'sensitive data', 'exfiltrating', 'uploading'],
        'techniques': ['T1048', 'T1041', 'T1005', 'T1560'],
        'weight': 0.88
    },
    'privilege_escalation': {
        'keywords': ['privilege escalation', 'privesc', 'sudo', 'root access', 'admin rights',
                     'uac bypass', 'uac', 'setuid', 'token impersonation', 'elevated privileges',
                     'elevated', 'impersonation', 'bypass', 'local exploit', 'kernel exploit',
                     'local privilege', 'admin privilege', 'escalate', 'gaining root',
                     'root privileges', 'arbitrary code', 'authentication bypass',
                     'unauthenticated', 'without authentication', 'pre-auth'],
        'techniques': ['T1548', 'T1134', 'T1055', 'T1543', 'T1068'],
        'weight': 0.87
    },
    'lateral_movement': {
        'keywords': ['lateral movement', 'pivot', 'rdp', 'psexec', 'wmi', 'wmic', 'winrm', 'dcom', 'smb',
                     'pass the ticket', 'admin share', 'remote execution', 'remote desktop',
                     'remote access', 'internal network access', 'workstation to server',
                     'compromised admin', 'domain controller', 'active directory'],
        'techniques': ['T1021', 'T1080', 'T1570', 'T1047', 'T1021.006'],
        'weight': 0.83
    },
    'persistence': {
        'keywords': ['persistence', 'startup', 'registry', 'cron job', 'autorun', 
                     'scheduled task', 'service install', 'bootkit', 'run key', 
                     'hklm', 'startup folder', 'local account'],
        'techniques': ['T1053', 'T1547', 'T1543', 'T1547.001', 'T1136.001'],
        'weight': 0.80
    },
    'command_control': {
        'keywords': ['c2', 'c&c', 'command and control', 'beacon', 'callback', 
                     'reverse shell', 'tunnel', 'proxy', 'dns tunnel'],
        'techniques': ['T1071', 'T1095', 'T1048'],
        'weight': 0.87
    },
    'impact': {
        'keywords': ['ransomware', 'encrypt', 'wipe', 'destroy', 'service stop',
                     'disruption', 'defacement', 'sabotage', 'denial of service'],
        'techniques': ['T1486', 'T1485', 'T1489'],
        'weight': 0.9
    },
    'web_compromise': {
        'keywords': ['webshell', 'web shell', 'path traversal', 'directory traversal', 'sql injection',
                     'cve-'],
        'techniques': ['T1505.003', 'T1190'],
        'weight': 0.8
    },
    'discovery': {
        'keywords': ['net.exe', 'domain admins', 'whoami', 'ipconfig', 'systeminfo', 'ping'],
        'techniques': ['T1087.002', 'T1069.002', 'T1033', 'T1016', 'T1082'],
        'weight': 0.7
    }
}

SEVERITY_KEYWORDS = {
    SeverityLevel.CRITICAL: ['ransomware', 'data breach', 'complete compromise', 'root access', 
                              'critical vulnerability', 'zero day', '0day', 'apt', 'nation state',
                              'supply chain', 'emotet', 'ryuk', 'wannacry', 'lockbit', 'conti',
                              'encrypt', 'domain compromise',
                              'lsass', 'dcsync', 'golden ticket', 'skeleton key', 'ntds.dit'],
    SeverityLevel.HIGH: ['brute force', 'credential dump', 'lateral movement', 'exfiltration',
                         'backdoor', 'c2', 'privilege escalation', 'malware', 'trojan',
                         'pass the hash', 'pass-the-hash', 'kerberoasting', 'mimikatz',
                         'cobalt strike', 'process injection', 'psexec', 'wmi execution',
                         'unauthorized access', 'data theft', 'stolen credentials',
                         'spear-phishing', 'targeted email', 'macro', 'ntlm hash',
                         'domain enumeration', 'bloodhound', 'crackmapexec', 'empire',
                         'secretsdump', 'sysvol', 'gpo'],
    SeverityLevel.MEDIUM: ['phishing', 'sql injection', 'xss', 'port scan', 'suspicious',
                            'anomaly', 'failed login', 'path traversal', 'directory traversal',
                            'cross-site scripting', 'csrf', 'ssrf', 'xxe', 'file inclusion'],
    SeverityLevel.LOW: ['scan', 'probe', 'reconnaissance', 'information gathering', 'log',
                        'normal', 'standard', 'routine', 'authorized']
}

# Merge auto-generated ATT&CK keywords into THREAT_SIGNATURES (no-op if not yet trained)
_load_expanded_keywords()

TACTICAL_MITIGATIONS = {
    'T1190': [
        MitigationStep(title="Deploy Web Application Firewall", description="Implement a WAF to filter malicious HTTP traffic and block common web attack patterns.", priority="Critical", effort="Medium"),
        MitigationStep(title="Patch Public-Facing Applications", description="Regularly update and patch all internet-facing applications, prioritizing critical security updates.", priority="Critical", effort="Low"),
        MitigationStep(title="Input Validation & Sanitization", description="Implement strict server-side input validation and output encoding to prevent injection attacks.", priority="High", effort="Medium")
    ],
    'T1110': [
        MitigationStep(title="Implement Multi-Factor Authentication", description="Enable MFA on all accounts, especially administrative and privileged access accounts.", priority="Critical", effort="Low"),
        MitigationStep(title="Account Lockout Policy", description="Configure account lockout after 5 failed attempts with a 30-minute lockout duration.", priority="High", effort="Low"),
        MitigationStep(title="Password Complexity Requirements", description="Enforce strong password policies: minimum 12 characters, complexity requirements, no reuse.", priority="High", effort="Low")
    ],
    'T1566': [
        MitigationStep(title="Email Security Gateway", description="Deploy anti-phishing email gateway with DMARC, DKIM, SPF enforcement and URL rewriting.", priority="Critical", effort="Medium"),
        MitigationStep(title="Security Awareness Training", description="Conduct regular phishing simulation training for all employees quarterly.", priority="High", effort="Low"),
        MitigationStep(title="Sandbox Email Attachments", description="Automatically sandbox all email attachments before delivery to detect malicious payloads.", priority="High", effort="Medium")
    ],
    'T1486': [
        MitigationStep(title="Offline Backup Strategy", description="Maintain 3-2-1 backup strategy: 3 copies, 2 media types, 1 offsite/offline backup. Test regularly.", priority="Critical", effort="Medium"),
        MitigationStep(title="Endpoint Detection & Response", description="Deploy EDR solution to detect ransomware execution patterns and enable automatic containment.", priority="Critical", effort="High"),
        MitigationStep(title="Network Segmentation", description="Segment the network to limit ransomware propagation. Restrict lateral movement via firewall rules.", priority="High", effort="High")
    ],
    'T1078': [
        MitigationStep(title="Privileged Access Management", description="Implement PAM solution to manage, monitor, and rotate privileged account credentials.", priority="Critical", effort="High"),
        MitigationStep(title="Zero Trust Architecture", description="Adopt Zero Trust model - verify every user and device before granting access to resources.", priority="High", effort="High"),
        MitigationStep(title="Credential Exposure Monitoring", description="Monitor dark web and breach databases for leaked organizational credentials.", priority="High", effort="Medium")
    ],
    'T1055': [
        MitigationStep(title="Enable Process Protection", description="Enable Windows Credential Guard and Protected Users security group to prevent process injection.", priority="High", effort="Low"),
        MitigationStep(title="Application Whitelisting", description="Implement application whitelisting to prevent unauthorized code execution.", priority="High", effort="High"),
        MitigationStep(title="Memory Protection Controls", description="Enable DEP/NX bit and ASLR on all systems to make exploitation significantly harder.", priority="Medium", effort="Low")
    ]
}

DEFAULT_MITIGATIONS = [
    MitigationStep(title="Enable Comprehensive Logging", description="Ensure all systems ship logs to a centralized SIEM for correlation and threat detection.", priority="High", effort="Medium"),
    MitigationStep(title="Network Traffic Analysis", description="Deploy NTA/NDR solution to detect anomalous network behavior and C2 communications.", priority="High", effort="High"),
    MitigationStep(title="Vulnerability Management", description="Run regular vulnerability scans and prioritize patching using CVSS scores.", priority="Medium", effort="Medium"),
    MitigationStep(title="Incident Response Plan", description="Develop and regularly test an incident response playbook for rapid containment.", priority="High", effort="Low")
]


def calculate_confidence(text: str, signature_keywords: list) -> float:
    """Calculate confidence score based on keyword density.
    Uses word-boundary matching to prevent substring false positives
    (e.g. 'login attempt' should NOT match 'User login from authorized device').
    Requires at least 2 keyword matches to return non-zero confidence.
    """
    text_lower = text.lower()
    matches = 0
    for kw in signature_keywords:
        # Multi-word keywords: require exact phrase match
        # Single-word keywords: require word boundary match
        if ' ' in kw:
            if kw in text_lower:
                matches += 1
        else:
            import re
            if re.search(r'\b' + re.escape(kw) + r'\b', text_lower):
                matches += 1
    # With precise heuristic buckets, requiring even 1 highly specific match is often enough
    # Example: "mimikatz" strongly implies T1003. We shouldn't require 2 separate keywords.
    if matches < 1:
        return 0.0
    
    # Scale based on 2 highly specific matches maxing out the heuristic confidence
    return min(0.95, 0.5 + (matches / 2.0) * 0.45)


def classify_threats(processed_input: Dict[str, Any]) -> Dict[str, float]:
    """Classify threat types from processed input and return their base confidence."""
    text = processed_input.get('normalized_text', '')
    detected = {}
    
    # 1. Use pre-suggested techniques from input processor
    for tech_id in processed_input.get('suggested_techniques', []):
        detected[tech_id] = 0.90

    # 2. Stage 1 Nano Pipeline: SecBERT Classification (Deep Learning TRAM)
    from core.secbert_classifier import secbert_clf
    
    # Try SecBERT first, as it has 90%+ accuracy natively on TRAM text
    ml_predictions = secbert_clf.predict_techniques(text)
    
    if ml_predictions:
        # If SecBERT worked, use its exact scores
        for tech_id, conf in ml_predictions.items():
            detected[tech_id] = conf
            
    else:
        # Fallback to the older TF-IDF Logistic Regression if SecBERT fails to load (0 M1 Memory)
        if technique_classifier:
            backup_predictions = technique_classifier.predict(text)
            for tech_id, conf in backup_predictions:
                visual_conf = min(0.96, (conf * 3.5) + 0.35)
                detected[tech_id] = visual_conf
            
    # 3. Apply Heuristic signature detection as a safety net
    # If ML misses obvious structural things (like specific registry keys or webshells)
    if len(detected) < 6:
        for threat_type, sig in THREAT_SIGNATURES.items():
            confidence = calculate_confidence(text, sig['keywords'])
            if confidence > 0.58: # Balanced heuristic threshold
                for t in sig['techniques']:
                    if t not in detected:
                        detected[t] = confidence
    
    return detected


def determine_severity(text: str, technique_ids: List[str]) -> Tuple[SeverityLevel, float, float]:
    """Determine severity, likelihood, and impact scores."""
    text_lower = text.lower()
    
    # Check for severity indicators
    for severity, keywords in SEVERITY_KEYWORDS.items():
        if any(kw in text_lower for kw in keywords):
            if severity == SeverityLevel.CRITICAL:
                return SeverityLevel.CRITICAL, 4.5, 5.0
            elif severity == SeverityLevel.HIGH:
                return SeverityLevel.HIGH, 3.5, 4.0
            elif severity == SeverityLevel.MEDIUM:
                return SeverityLevel.MEDIUM, 2.5, 3.0
    
    # Base severity on number of técnicas detected
    if len(technique_ids) >= 4:
        return SeverityLevel.HIGH, 3.0, 3.5
    elif len(technique_ids) >= 2:
        return SeverityLevel.MEDIUM, 2.0, 2.5
    else:
        return SeverityLevel.LOW, 1.5, 1.5


def get_attack_techniques(technique_scores: Dict[str, float], text: str) -> List[ATTACKTechnique]:
    """Get full technique objects with real semantic confidence scores."""
    technique_ids = list(technique_scores.keys())
    techniques = []
    seen = set()

    # Batch-compute real cosine similarity scores for all technique IDs at once
    semantic_scores = technique_embedder.batch_score_techniques(text, technique_ids)

    for technique in _ATTACK_DB:
        if technique['id'] in technique_ids and technique['id'] not in seen:
            seen.add(technique['id'])

            # ML or Heuristic base confidence
            base_conf = technique_scores.get(technique['id'], 0.5)
            # Semantic contextual match confidence
            semantic_conf = semantic_scores.get(technique['id'], 0.5)

            # Smart confidence blending
            if semantic_conf >= 0.45:
                # Strong semantic link: trust the base confidence
                confidence = max(base_conf, semantic_conf)
                if confidence > 0.5:
                    confidence = min(0.99, confidence)
            else:
                # Weak semantic link: likely just context or a co-occurrence ML prediction
                # We pull it down to visually separate it, but keep it >70% so it indicates strong ML probability
                confidence = (base_conf * 0.8) + (semantic_conf * 0.2)

            confidence = round(confidence, 2)

            techniques.append(ATTACKTechnique(
                id=technique['id'],
                name=technique['name'],
                tactic=technique['tactic'],
                tactic_id=technique['tactic_id'],
                description=technique['description'],
                confidence=confidence
            ))

    sorted_techniques = sorted(techniques, key=lambda t: t.confidence, reverse=True)
    
    # Filter out low confidence speculative results. Since we boosted the blend, 
    # anything below 0.65 is genuinely low probability noise.
    filtered_techniques = [t for t in sorted_techniques if t.confidence >= 0.65]
    
    # Dynamically cap the results based on confidence tiers
    final_techniques = []
    for t in filtered_techniques:
        if t.confidence >= 0.90:
            final_techniques.append(t)  # Include all very high confidence techniques (no cap)
        elif t.confidence >= 0.75:
            # Include medium-high confidence techniques, up to a total list size of 6
            if len(final_techniques) < 6:
                final_techniques.append(t)
        else:
            # Include standard confidence techniques (0.65 - 0.74), up to a total list size of 4
            if len(final_techniques) < 4:
                final_techniques.append(t)
                
    return final_techniques


def get_mitigations(technique_ids: List[str]) -> List[MitigationStep]:
    """Get mitigation steps for detected techniques."""
    mitigations = []
    seen_titles = set()
    
    for tech_id in technique_ids[:5]:  # Top 5 techniques
        if tech_id in TACTICAL_MITIGATIONS:
            for m in TACTICAL_MITIGATIONS[tech_id]:
                if m.title not in seen_titles:
                    seen_titles.add(m.title)
                    mitigations.append(m)
    
    # Add defaults if we don't have enough
    for m in DEFAULT_MITIGATIONS:
        if m.title not in seen_titles and len(mitigations) < 8:
            seen_titles.add(m.title)
            mitigations.append(m)
    
    return mitigations[:6]


def generate_business_impact(severity: SeverityLevel, technique_ids: List[str]) -> str:
    """Generate business impact narrative."""
    impacts = {
        SeverityLevel.CRITICAL: "Severe business disruption risk. Potential for complete system compromise, significant data breach, financial loss, and regulatory penalties. Immediate executive escalation required.",
        SeverityLevel.HIGH: "Significant business risk. Could lead to data exposure, service disruption, and reputational damage. Executive notification and emergency response required.",
        SeverityLevel.MEDIUM: "Moderate business impact. Contains risk of limited data exposure or service degradation. Prompt remediation required within 72 hours.",
        SeverityLevel.LOW: "Low business impact. Represents reconnaissance or early-stage threat activity. Monitor closely and remediate within SLA."
    }
    
    # Add technique-specific context
    if 'T1486' in technique_ids:
        return "RANSOMWARE RISK: " + impacts.get(severity, "Unknown impact")
    if 'T1048' in technique_ids or 'T1041' in technique_ids:
        return "DATA EXFILTRATION RISK: " + impacts.get(severity, "Unknown impact")
    
    return impacts.get(severity, "Unknown business impact")


# Technique → human-readable tactic stage labels
_TACTIC_STAGE = {
    'T1190': 'Initial Access via Vulnerability Exploitation',
    'T1566': 'Spear-Phishing / Initial Access',
    'T1059': 'Execution via Scripting Interpreter',
    'T1059.001': 'PowerShell-Based Execution',
    'T1053': 'Scheduled Task Persistence',
    'T1055': 'Process Injection',
    'T1003': 'Credential Dumping (LSASS / SAM)',
    'T1078': 'Valid Account Abuse',
    'T1110': 'Brute Force / Password Attack',
    'T1021': 'Lateral Movement via Remote Services',
    'T1080': 'Lateral Movement via Shared Content',
    'T1071': 'C2 via Application Layer Protocol',
    'T1095': 'C2 via Non-Application Layer Protocol',
    'T1048': 'Exfiltration over Alternative Protocol',
    'T1041': 'Exfiltration over C2 Channel',
    'T1486': 'Data Encryption for Impact (Ransomware)',
    'T1485': 'Data Destruction',
    'T1560': 'Data Archiving for Exfiltration',
    'T1548': 'Privilege Escalation via Abuse of Mechanism',
    'T1134': 'Privilege Escalation via Token Impersonation',
    'T1068': 'Exploitation for Privilege Escalation',
    'T1547': 'Boot/Logon Autostart Persistence',
    'T1543': 'System Service Persistence',
    'T1046': 'Network Service Discovery/Scanning',
    'T1040': 'Network Sniffing/Traffic Interception',
    'T1558': 'Kerberos Ticket Theft',
    'T1555': 'Credential Access from Password Stores',
    'T1570': 'Lateral Tool Transfer',
    'T1489': 'Service Stop / Disruptive Impact',
}

# Priority ordering: later kill-chain stages first in title selection
_TITLE_PRIORITY = [
    ('T1486', 'Ransomware Attack'), ('T1485', 'Data Destruction Attack'),
    ('T1048', 'Data Exfiltration via DNS/Alternative Channel'),
    ('T1041', 'Data Exfiltration via C2 Channel'),
    ('T1560', 'Data Staging and Exfiltration'),
    ('T1003', 'Credential Dumping Attack'), ('T1558', 'Kerberos Credential Theft'),
    ('T1078', 'Compromised Credential Abuse'),
    ('T1021', 'Lateral Movement Attack'), ('T1080', 'Internal Network Lateral Movement'),
    ('T1071', 'Covert C2 Communication'), ('T1095', 'Covert C2 Communication'),
    ('T1055', 'Process Injection / Defense Evasion'),
    ('T1068', 'Local Privilege Escalation'),
    ('T1548', 'Privilege Escalation'),
    ('T1059', 'Malicious Script Execution'), ('T1059.001', 'PowerShell Attack'),
    ('T1053', 'Scheduled Task / Persistence Mechanism'),
    ('T1566', 'Phishing Campaign'), ('T1190', 'Vulnerability Exploitation'),
    ('T1046', 'Network Reconnaissance'), ('T1040', 'Network Traffic Interception'),
    ('T1110', 'Brute Force Credential Attack'),
]


def _get_threat_title(technique_ids: List[str], entities: List[Any]) -> str:
    """Generate meaningful threat title based on highest-priority detected technique."""
    for tech_id, label in _TITLE_PRIORITY:
        if tech_id in technique_ids:
            return f"Detected: {label}"
    # Fallback: use the first technique's tactic if we have an attack DB
    if _ATTACK_DB and technique_ids:
        for tech in _ATTACK_DB:
            if tech['id'] == technique_ids[0]:
                return f"Detected: {tech['name']} — {tech['tactic']}"
    return "Detected: Multi-Stage Cyber Threat"


def _extract_entities(text: str) -> List[Dict[str, str]]:
    """
    Extract specific entities (tools, malware, CVEs, IPs, domains) using 
    both structured regex and spaCy NER (if available).
    Returns a unified list of entity dictionaries.
    """
    entities = []
    text_lower = text.lower()
    
    # 1. Regex-based extraction (high precision)
    cves = re.findall(r'CVE-\d{4}-\d{4,7}', text, re.IGNORECASE)
    for cve in set(cves):
        entities.append({'type': 'cve', 'value': cve.upper()})
        
    ips = re.findall(r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b', text)
    for ip in set(ips):
        entities.append({'type': 'ip', 'value': ip})
        
    hashes = re.findall(r'\b[a-fA-F0-9]{32,64}\b', text)
    for h in set(hashes):
        entities.append({'type': 'hash', 'value': h})

    domains = re.findall(r'\b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]\b', text_lower)
    for domain in set(domains):
        # Exclude common false positives
        if domain not in ('exe', 'dll', 'com', 'bat', 'sh', 'txt') and len(domain) > 4:
             if domain not in [e['value'] for e in entities if e['type'] == 'ip']:
                 entities.append({'type': 'domain', 'value': domain})

    # 2. Known Dictionary extraction (high precision)
    known_tools = [
        'mimikatz', 'cobalt strike', 'metasploit', 'cobaltstrike',
        'meterpreter', 'beacon', 'bloodhound', 'sharphound', 'impacket',
        'psexec', 'powershell', 'wmiexec', 'crackmapexec', 'empire',
        'emotet', 'ryuk', 'lockbit', 'conti', 'blackcat', 'alphv',
        'wannacry', 'petya', 'notpetya', 'darkside', 'revil', 'sodinokibi',
        'lazarus', 'apt28', 'apt29', 'apt41', 'fin7', 'carbanak',
        '7-zip', '7zip', 'winrar', 'certutil', 'bitsadmin', 'regsvr32',
        'mshta', 'wscript', 'cscript', 'rundll32', 'schtasks', 'at.exe',
        'nltest', 'secretsdump', 'procdump', 'nmap', 'sqlmap', 'burpsuite'
    ]
    for t in known_tools:
        if t in text_lower:
            entities.append({'type': 'tool', 'value': t})

    # 3. spaCy NER (extracts proper nouns we might have missed)
    if _nlp:
        doc = _nlp(text)
        for ent in doc.ents:
            # We are interested in Organizations (often malware/groups), Products, and Persons
            if ent.label_ in ['ORG', 'PRODUCT', 'PERSON']:
                val = ent.text.strip()
                # Exclude if it's already in our dictionary or regex hits
                val_lower = val.lower()
                if len(val) > 2 and not any(val_lower in e['value'].lower() for e in entities) and val_lower not in known_tools:
                    # Generic filter
                    if val_lower not in ['microsoft', 'windows', 'linux', 'apple', 'google', 'aws']:
                        entities.append({'type': 'organization/product', 'value': val})
    
    # Deduplicate while preserving order
    seen = set()
    unique_entities = []
    for e in entities:
        # Create a lowercase hashable key
        k = f"{e['type']}:{e['value'].lower()}"
        if k not in seen:
            seen.add(k)
            unique_entities.append(e)
            
    return unique_entities


def generate_predictive_actions(technique_ids: List[str], text: str = '', entities: List[Any] = None) -> str:
    """
    Generate a DYNAMIC prediction narrative based on the SPECIFIC techniques,
    tools, and CVEs detected — not a generic template.
    """
    if entities is None:
        entities = []
    if not technique_ids:
        return "No threat-specific patterns were detected. If this was flagged as suspicious, review system logs for unusual process execution or network connections."

    # Extract comprehensive entities using NER and regex
    extracted_entities = _extract_entities(text)
    
    detected_tools = [e['value'] for e in extracted_entities if e['type'] == 'tool']
    detected_cves = [e['value'] for e in extracted_entities if e['type'] == 'cve']
    
    # Pre-populate input entities with our extractions so they show up in the UI
    for ext_e in extracted_entities:
        if not any(isinstance(e, dict) and e.get('value', '').lower() == ext_e['value'].lower() for e in entities):
            try:
                # Add as ThreatEntity schema-compatible dict
                entities.append({
                    'type': ext_e['type'],
                    'value': ext_e['value'],
                    'context': 'NLP Extracted'
                })
            except Exception:
                pass
    parts = []

    # --- Build the narrative from actual detected evidence ---

    # 1. Describe current stage clearly
    current_stages = [_TACTIC_STAGE[t] for t in technique_ids if t in _TACTIC_STAGE]
    if current_stages:
        unique_stages = list(dict.fromkeys(current_stages))  # preserve order, deduplicate
        parts.append(f"Current activity: {'; '.join(unique_stages[:4])}.")

    # 2. Tool-specific context
    if detected_tools:
        tool_names = ', '.join(t.title() for t in detected_tools[:5])
        parts.append(f"Specific tools/malware observed: {tool_names}.")

    # 3. CVE-specific context
    if detected_cves:
        cve_str = ', '.join(detected_cves[:3])
        parts.append(f"Vulnerability exploit attempted: {cve_str}.")

    # 4. Next-step prediction based on kill-chain position
    has_initial_access = any(t in technique_ids for t in ['T1190', 'T1566', 'T1133', 'T1091'])
    has_execution = any(t in technique_ids for t in ['T1059', 'T1059.001', 'T1053', 'T1055'])
    has_cred_access = any(t in technique_ids for t in ['T1003', 'T1110', 'T1078', 'T1555', 'T1558'])
    has_lateral = any(t in technique_ids for t in ['T1021', 'T1080', 'T1570'])
    has_c2 = any(t in technique_ids for t in ['T1071', 'T1095', 'T1048', 'T1041'])
    has_impact = any(t in technique_ids for t in ['T1486', 'T1485', 'T1489'])
    has_exfil = any(t in technique_ids for t in ['T1041', 'T1048', 'T1560', 'T1005'])

    predictions = []

    if has_impact or has_exfil:
        predictions.append(
            "URGENT: The attacker has reached the final objective phase. "
            + ("Ransomware encryption is likely active — immediately isolate affected hosts, revoke domain credentials, and activate IR playbook. " if 'T1486' in technique_ids else "")
            + ("Data exfiltration is in progress — block outbound traffic on DNS/HTTPS to untrusted destinations. " if has_exfil else "")
        )
    elif has_lateral and has_cred_access:
        loc = 'via RDP, SMB, or WMI' if 'T1021' in technique_ids else 'across internal systems'
        predictions.append(
            f"The attacker is conducting lateral movement {loc} using stolen credentials. "
            "Expect immediate targeting of domain controllers, backup servers, and file shares. "
            "Expect ransomware deployment or sensitive data staging within hours."
        )
    elif has_cred_access:
        dump_method = ''
        if 'T1003' in technique_ids:
            dump_method = ' via LSASS memory dump or SAM database'
        elif 'T1558' in technique_ids:
            dump_method = ' via Kerberos ticket theft (Kerberoasting/Pass-the-Ticket)'
        predictions.append(
            f"The attacker has obtained credentials{dump_method}. "
            "Next step: lateral movement across the domain using pass-the-hash, pass-the-ticket, or direct RDP/SMB. "
            "Rotate all domain credentials immediately and enable Credential Guard."
        )
    elif has_execution and has_initial_access:
        exe_method = 'PowerShell' if 'T1059.001' in technique_ids else 'scripting interpreter'
        predictions.append(
            f"The attacker has achieved initial access and is executing commands via {exe_method}. "
            "Expect immediate privilege escalation attempts (UAC bypass, local exploits) "
            "and credential harvesting. Deploy EDR containment on affected endpoints now."
        )
    elif has_initial_access:
        vuln_str = f" ({', '.join(detected_cves)})" if detected_cves else ''
        predictions.append(
            f"Initial access was established via vulnerability exploitation{vuln_str}. "
            "The attacker will next attempt to deploy a persistent backdoor or C2 implant, "
            "then begin internal reconnaissance. Patch the exploited service and isolate the host immediately."
        )
    elif has_c2:
        c2_proto = 'DNS tunneling' if 'T1048' in technique_ids else 'HTTPS/application-layer protocol'
        predictions.append(
            f"An active C2 channel is established ({c2_proto}). "
            "The attacker has implant(s) running on internal hosts awaiting tasking. "
            "Block outbound C2 traffic via firewall rules and hunt for implant processes on all endpoints."
        )
    else:
        predictions.append(
            "The attacker is in an early-stage reconnaissance or execution phase. "
            "Monitor for escalating activity: increased failed logins, unusual process spawning, "
            "or unexpected outbound connections to unfamiliar external IPs."
        )

    return ' '.join(p.strip() for p in parts + predictions if p.strip())



def analyze_threat(processed_input: Dict[str, Any], deep_analysis: bool = False) -> ThreatResult:
    """
    Main industrial-grade threat analysis function.
    Orchestrates the two-stage AI pipeline (SecBERT + Phi-3.5) with heuristic baselines.
    """
    text = processed_input.get('normalized_text', '')
    entities = processed_input.get('entities', [])

    # 1. Heuristic Baseline Scoring (Fast)
    technique_scores = classify_threats(processed_input)
    # determine_severity returns (severity, likelihood, impact) as enums/floats
    severity, likelihood, impact = determine_severity(text, list(technique_scores.keys()))
    
    # Calculate initial CVSS-inspired score (0-10)
    base_score = float(round((likelihood * 0.4 + impact * 0.6) * 2, 1))
    base_score = min(10.0, base_score)

    # 2. Industrial ML Ensemble (SecBERT + Phi-3.5)
    # evaluate_threat performs Stage 1 (TTP mapping) and Stage 2 (LLM reasoning)
    is_anomalous, final_score, deep_insights = ml_engine.evaluate_threat(processed_input, base_score, deep_analysis=deep_analysis)
    
    # 3. Final Result Construction
    final_techniques_list = []
    if deep_analysis and deep_insights:
        # TTPs from ML Engine Stage 3 already contain name, confirmed ID, and verified status
        detected_ttps = deep_insights.get("ttps", [])
        
        for ttp in detected_ttps:
            # Propagate "Verified" status and evidence to the final result
            final_techniques_list.append(ATTACKTechnique(
                id=ttp.get("id"),
                name=ttp.get("name", "Classified Technique"),
                tactic="Multiple Tactics", # This will be filled by get_attack_techniques if needed
                confidence=float(round(ttp.get("confidence", 0.5), 2)),
                verified=ttp.get("verified", False),
                evidence=ttp.get("evidence", [])
            ))
    
    if not final_techniques_list: # Fallback if deep_analysis didn't yield TTPs or wasn't enabled
        # Fallback to TRAM keywords if ML Stage 1 failed or is loading
        for tid, conf in technique_scores.items():
            final_techniques_list.append(ATTACKTechnique(
                id=tid, 
                name="Classified Technique", 
                tactic="Multiple Tactics", 
                confidence=float(round(conf, 2))
            ))

    # Map score to standard SeverityLevel
    mapped_severity = SeverityLevel.LOW
    if final_score >= 9.0: mapped_severity = SeverityLevel.CRITICAL
    elif final_score >= 7.0: mapped_severity = SeverityLevel.HIGH
    elif final_score >= 4.0: mapped_severity = SeverityLevel.MEDIUM

    # Framework Mappings (NIST, D3FEND, OWASP)
    tech_ids = [t.id for t in final_techniques_list]
    
    result = ThreatResult(
        id=str(uuid.uuid4()),
        title=deep_insights.get("title", f"AI Analysis: Threat Activity Detected"),
        timestamp=datetime.now(),
        description=deep_insights.get("summary", "Heuristic patterns detected."),
        risk_score=RiskScore(
            score=float(round(final_score, 1)),
            severity=mapped_severity,
            likelihood=float(likelihood) if not is_anomalous else 0.8,
            impact=float(impact),
            business_impact=deep_insights.get("analysis", "AI analysis identifies potential risk to organizational pillars.")
        ),
        attack_techniques=final_techniques_list,
        defend_countermeasures=map_to_defend(tech_ids),
        nist_controls=map_to_nist(tech_ids),
        owasp_items=map_to_owasp(tech_ids),
        mitigations=get_mitigations(tech_ids),
        entities=[ThreatEntity(type=e.get('type', 'indicator'), value=e.get('value', '')) for e in entities],
        raw_indicators={
            "technique_ids": tech_ids,
            "is_anomaly": is_anomalous,
            "deep_extraction": deep_insights.get("terms", []),
            "technical_dive": deep_insights.get("analysis", "")
        }
    )
    return result
    return result
