"""
AI Threat Analyzer Module
Performs hybrid rule-based + NLP threat detection and classification.
Uses sklearn for ML classification, NLTK for text processing, and
regex-based pattern matching for rule-based detection.
"""
import json
import re
import os
import uuid
from datetime import datetime
from typing import List, Tuple, Dict, Any
import numpy as np
from dotenv import load_dotenv

load_dotenv()

try:
    import spacy
    # Load the English NLP model (will fail gracefully if not installed yet)
    _nlp = spacy.load("en_core_web_sm")
except Exception:
    _nlp = None

try:
    from core import technique_classifier
except ImportError:
    technique_classifier = None

from models.schemas import (
    ATTACKTechnique, ThreatResult, RiskScore, SeverityLevel,
    ThreatEntity, MitigationStep, PredictedStep
)
from core.llm_engine import LocalHuggingFaceEngine
from core.ml_engine import ml_engine
from core.framework_mapper import map_to_defend, map_to_nist, map_to_owasp
from core import technique_embedder

llama_rag = LocalHuggingFaceEngine()

# Load ATT&CK database at module level
_ATTACK_DB = None
_ATTACK_LOOKUP = {} # Added for fast ID -> metadata lookup
_DEFEND_DB = None
_NIST_DB = None
_OWASP_DB = None

# Expanded ATT&CK keywords (auto-generated by scripts/train_real_data.py)
_DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data')
_EXPANDED_KW_PATH = os.path.join(_DATA_DIR, 'attack_keywords.json')
_EXPANDED_KW: Dict[str, list] = {}

# Generic words that appear in normal text and cause false positives
_GENERIC_STOPWORDS = {
    'code', 'network', 'user', 'device', 'remote', 'data', 'system', 'file',
    'server', 'service', 'access', 'process', 'execution', 'information',
    'application', 'software', 'security', 'control', 'command', 'time',
    'host', 'port', 'client', 'protocol', 'connection', 'session',
    'value', 'name', 'path', 'key', 'type', 'response', 'request',
    'update', 'change', 'log', 'event', 'error', 'message', 'source',
    'target', 'object', 'group', 'list', 'table', 'record', 'account',
    'authentication', 'configuration', 'monitor', 'run', 'management', 'injection'
}

def _load_expanded_keywords():
    """Load auto-generated ATT&CK keyword expansions and merge into THREAT_SIGNATURES.
    Filters out generic single-word keywords that cause false positives."""
    global _EXPANDED_KW
    if not os.path.exists(_EXPANDED_KW_PATH):
        return  # Not yet trained — silently skip
    try:
        with open(_EXPANDED_KW_PATH) as f:
            _EXPANDED_KW = json.load(f)
        # Merge expanded keywords into existing THREAT_SIGNATURES
        for category, kw_list in _EXPANDED_KW.items():
            if category in THREAT_SIGNATURES:
                existing = set(THREAT_SIGNATURES[category]['keywords'])
                # Only add multi-word phrases or specific single words (not generic ones)
                new_kws = []
                for k in kw_list:
                    if k in existing:
                        continue
                    # Filter out generic single-word keywords
                    if ' ' not in k and k.lower() in _GENERIC_STOPWORDS:
                        continue
                    # Skip very short words (3 chars or less) unless multi-word
                    if ' ' not in k and len(k) <= 3:
                        continue
                    new_kws.append(k)
                THREAT_SIGNATURES[category]['keywords'].extend(new_kws[:30])
            # else: new category — only add if it maps to a known one
        import logging
        logging.getLogger(__name__).info(
            f"Loaded ATT&CK expanded keywords: "
            f"{sum(len(v) for v in _EXPANDED_KW.values())} keywords across {len(_EXPANDED_KW)} categories"
        )
    except Exception as e:
        import logging
        logging.getLogger(__name__).warning(f"Could not load expanded ATT&CK keywords: {e}")



def _load_databases():
    global _ATTACK_DB, _ATTACK_LOOKUP, _DEFEND_DB, _NIST_DB, _OWASP_DB
    base = os.path.join(os.path.dirname(__file__), '..', 'data')
    try:
        with open(os.path.join(base, 'mitre_attack.json')) as f:
            _ATTACK_DB = json.load(f)
            # Build lookup for performance
            _ATTACK_LOOKUP = {t['id']: t for t in _ATTACK_DB}
        with open(os.path.join(base, 'mitre_defend.json')) as f:
            _DEFEND_DB = json.load(f)
        with open(os.path.join(base, 'nist_controls.json')) as f:
            _NIST_DB = json.load(f)
        with open(os.path.join(base, 'owasp_data.json')) as f:
            _OWASP_DB = json.load(f)
    except Exception as e:
        import logging
        logging.getLogger(__name__).error(f"Failed to load threat databases: {e}")

_load_databases()

# NOTE: _load_expanded_keywords() is called AFTER THREAT_SIGNATURES is defined (see end of signatures block)

# Kick off technique embedding precomputation in a background thread so startup is non-blocking
import threading
_embed_thread = threading.Thread(target=technique_embedder.precompute_technique_embeddings, daemon=True)
_embed_thread.start()



# Threat classification keyword sets with weights
THREAT_SIGNATURES = {
    'web_attack': {
        'keywords': ['sql injection', 'xss', 'cross-site', 'csrf', 'ssrf', 'xxe', 
                     'path traversal', 'directory traversal', 'file inclusion', 
                     'remote file', 'http flood', 'web application', 'api abuse',
                     'buffer overflow', 'heap overflow', 'stack overflow',
                     'remote code execution', 'arbitrary code execution',
                     'code execution', 'command injection', 'code injection',
                     'use after free', 'use-after-free', 'memory corruption',
                     'integer overflow', 'format string', 'out of bounds'],
        'techniques': ['T1190', 'T1190.001', 'T1190.002', 'T1203'],
        'weight': 0.9
    },
    'credential_dumping': {
        'keywords': ['mimikatz', 'dump credentials', 'dumped credentials', 'credentials dump', 
                     'credential dump', 'lsass', 'sam database', 'hashdump', 'secretsdump'],
        'techniques': ['T1003'],
        'weight': 0.88
    },
    'credential_brute_force': {
        'keywords': ['brute force', 'password spray', 'credential stuffing', 'login attempt',
                     'authentication failure', 'invalid password', 'account lockout'],
        'techniques': ['T1110'],
        'weight': 0.87
    },
    'credential_pass_hash': {
        'keywords': ['pass the hash', 'pass-the-hash', 'pth', 'ntlm hash', 'hash used to authenticate'],
        'techniques': ['T1555'],
        'weight': 0.86
    },
    'credential_kerberos': {
        'keywords': ['kerberoasting', 'golden ticket', 'silver ticket', 'dcsync'],
        'techniques': ['T1558', 'T1003'],
        'weight': 0.89
    },
    'malware_ransomware': {
        'keywords': ['ransomware', 'ryuk', 'wannacry', 'darkside', 'petya', 'notpetya', 
                     'lockbit', 'blackcat', 'alphv', 'conti', 'revil', 'cryptolocker'],
        'techniques': ['T1486'],
        'weight': 0.95
    },
    'malware_backdoor_trojan': {
        'keywords': ['trojan', 'backdoor', 'rootkit', 'spyware', 'keylogger', 'botnet', 
                     'worm', 'virus', 'rat', 'payload', 'dropper', 'loader', 'cobalt strike', 
                     'metasploit', 'emotet', 'lazarus', 'apt28', 'apt29',
                     'macro payload', 'malicious document', 'mirai'],
        'techniques': ['T1059', 'T1055', 'T1027', 'T1566'],
        'weight': 0.9
    },
    'network_attack': {
        'keywords': ['port scan', 'network scan', 'nmap', 'reconnaissance', 'syn flood',
                     'ddos', 'dos attack', 'packet', 'sniff', 'arp poison', 'mitm',
                     'man in the middle', 'dns poison', 'spoofing'],
        'techniques': ['T1046', 'T1040', 'T1071', 'T1095'],
        'weight': 0.8
    },
    'data_exfiltration': {
        'keywords': ['data exfiltration', 'data theft', 'exfil', 'data breach', 'leak',
                     'stolen data', 'sensitive data', 'exfiltrating', 'uploading'],
        'techniques': ['T1048', 'T1041', 'T1005', 'T1560'],
        'weight': 0.88
    },
    'privilege_escalation': {
        'keywords': ['privilege escalation', 'privesc', 'sudo', 'root access', 'admin rights',
                     'uac bypass', 'uac', 'setuid', 'token impersonation', 'elevated privileges',
                     'elevated', 'impersonation', 'bypass', 'local exploit', 'kernel exploit',
                     'local privilege', 'admin privilege', 'escalate', 'gaining root',
                     'root privileges', 'arbitrary code', 'authentication bypass',
                     'unauthenticated', 'without authentication', 'pre-auth'],
        'techniques': ['T1548', 'T1134', 'T1055', 'T1543', 'T1068'],
        'weight': 0.87
    },
    'lateral_movement': {
        'keywords': ['lateral movement', 'pivot', 'rdp', 'psexec', 'wmi', 'wmic', 'winrm', 'dcom', 'smb',
                     'pass the ticket', 'admin share', 'remote execution', 'remote desktop',
                     'remote access', 'internal network access', 'workstation to server',
                     'compromised admin', 'domain controller', 'active directory'],
        'techniques': ['T1021', 'T1080', 'T1570', 'T1047', 'T1021.006'],
        'weight': 0.83
    },
    'persistence': {
        'keywords': ['persistence', 'startup', 'registry', 'cron job', 'autorun', 
                     'scheduled task', 'service install', 'bootkit', 'run key', 
                     'hklm', 'startup folder', 'local account'],
        'techniques': ['T1053', 'T1547', 'T1543', 'T1547.001', 'T1136.001'],
        'weight': 0.80
    },
    'command_control': {
        'keywords': ['c2', 'c&c', 'command and control', 'beacon', 'callback', 
                     'reverse shell', 'tunnel', 'proxy', 'dns tunnel'],
        'techniques': ['T1071', 'T1095', 'T1048'],
        'weight': 0.87
    },
    'impact': {
        'keywords': ['ransomware', 'encrypt', 'wipe', 'destroy', 'service stop',
                     'disruption', 'defacement', 'sabotage', 'denial of service'],
        'techniques': ['T1486', 'T1485', 'T1489'],
        'weight': 0.9
    },
    'web_shell_persistence': {
        'keywords': ['webshell', 'web shell', 'paws', 'b374k', 'c99shell', 'r57shell', 'china chopper'],
        'techniques': ['T1505.003'],
        'weight': 0.98
    },
    'discovery': {
        'keywords': ['net.exe', 'domain admins', 'whoami', 'ipconfig', 'systeminfo', 'ping'],
        'techniques': ['T1087.002', 'T1069.002', 'T1033', 'T1016', 'T1082'],
        'weight': 0.7
    }
}

SEVERITY_KEYWORDS = {
    SeverityLevel.CRITICAL: ['ransomware', 'data breach', 'complete compromise', 'root access', 
                              'critical vulnerability', 'zero day', '0day', 'apt', 'nation state',
                              'supply chain', 'emotet', 'ryuk', 'wannacry', 'lockbit', 'conti',
                              'encrypt', 'domain compromise',
                              'lsass', 'dcsync', 'golden ticket', 'skeleton key', 'ntds.dit'],
    SeverityLevel.HIGH: ['brute force', 'credential dump', 'lateral movement', 'exfiltration',
                         'backdoor', 'c2', 'privilege escalation', 'malware', 'trojan',
                         'pass the hash', 'pass-the-hash', 'kerberoasting', 'mimikatz',
                         'cobalt strike', 'process injection', 'psexec', 'wmi execution',
                         'unauthorized access', 'data theft', 'stolen credentials',
                         'spear-phishing', 'targeted email', 'macro', 'ntlm hash',
                         'domain enumeration', 'bloodhound', 'crackmapexec', 'empire',
                         'secretsdump', 'sysvol', 'gpo'],
    SeverityLevel.MEDIUM: ['phishing', 'sql injection', 'xss', 'port scan', 'suspicious',
                            'anomaly', 'failed login', 'path traversal', 'directory traversal',
                            'cross-site scripting', 'csrf', 'ssrf', 'xxe', 'file inclusion'],
    SeverityLevel.LOW: ['scan', 'probe', 'reconnaissance', 'information gathering', 'log',
                        'normal', 'standard', 'routine', 'authorized']
}

# Merge auto-generated ATT&CK keywords into THREAT_SIGNATURES (no-op if not yet trained)
_load_expanded_keywords()

TACTICAL_MITIGATIONS = {
    'T1190': [
        MitigationStep(title="Deploy Web Application Firewall", description="Implement a WAF to filter malicious HTTP traffic and block common web attack patterns like SQLi and XSS.", priority="Critical", effort="Medium"),
        MitigationStep(title="Input Validation & Sanitization", description="Implement strict server-side input validation and output encoding to prevent injection attacks.", priority="High", effort="Medium"),
        MitigationStep(title="Patch Public-Facing Applications", description="Regularly update and patch all internet-facing applications, prioritizing critical security updates.", priority="Critical", effort="Low")
    ],
    'T1110': [
        MitigationStep(title="Implement Multi-Factor Authentication", description="Enable MFA on all accounts, especially administrative and privileged access accounts.", priority="Critical", effort="Low"),
        MitigationStep(title="Account Lockout Policy", description="Configure account lockout after 5 failed attempts with a 30-minute lockout duration.", priority="High", effort="Low"),
        MitigationStep(title="Password Complexity Requirements", description="Enforce strong password policies: minimum 12 characters, complexity requirements, no reuse.", priority="High", effort="Low")
    ],
    'T1566': [
        MitigationStep(title="Email Security Gateway", description="Deploy anti-phishing email gateway with DMARC, DKIM, SPF enforcement and URL rewriting.", priority="Critical", effort="Medium"),
        MitigationStep(title="Security Awareness Training", description="Conduct regular phishing simulation training for all employees quarterly.", priority="High", effort="Low"),
        MitigationStep(title="Sandbox Email Attachments", description="Automatically sandbox all email attachments before delivery to detect malicious payloads.", priority="High", effort="Medium")
    ],
    'T1486': [
        MitigationStep(title="Offline Backup Strategy", description="Maintain 3-2-1 backup strategy: 3 copies, 2 media types, 1 offsite/offline backup. Test regularly.", priority="Critical", effort="Medium"),
        MitigationStep(title="Endpoint Detection & Response", description="Deploy EDR solution to detect ransomware execution patterns and enable automatic containment.", priority="Critical", effort="High"),
        MitigationStep(title="Inhibit System Recovery Protection", description="Monitor for unauthorized use of vssadmin.exe and other tools used to delete shadow copies.", priority="High", effort="Low")
    ],
    'T1003': [
        MitigationStep(title="Enable LSA Protection", description="Configure RunAsPPL for lsass.exe to prevent credential dumping tools like Mimikatz from accessing memory.", priority="Critical", effort="Low"),
        MitigationStep(title="Credential Guard", description="Enable Windows Defender Credential Guard to use virtualization-based security to isolate secrets.", priority="Critical", effort="Medium"),
        MitigationStep(title="Restrict Debug Privileges", description="Revoke 'Debug programs' (SeDebugPrivilege) for non-administrative users and specialized accounts.", priority="High", effort="Low")
    ],
    'T1021': [
        MitigationStep(title="Disable Unnecessary RDP", description="Disable Remote Desktop Services on workstations and servers where not strictly required.", priority="High", effort="Low"),
        MitigationStep(title="Network Level Authentication", description="Enforce Network Level Authentication (NLA) for RDP to require authentication before a session is started.", priority="High", effort="Low"),
        MitigationStep(title="RDP Gateway and VPN", description="Restrict RDP access to be available only through a secure VPN or an RDP Gateway.", priority="High", effort="Medium")
    ],
    'T1505.003': [
        MitigationStep(title="Server-Side File Integrity Monitoring", description="Deploy FIM to monitor web directories for the creation of unauthorized scripts and shells.", priority="High", effort="Medium"),
        MitigationStep(title="Principle of Least Privilege", description="Configure the web server process to run with the minimum necessary permissions, preventing shell execution.", priority="High", effort="Low"),
        MitigationStep(title="Disable Execution in Assets", description="Configure the web server to disable script execution in directories intended for static assets like images.", priority="High", effort="Low")
    ],
    'T1059.001': [
        MitigationStep(title="PowerShell Constrained Language Mode", description="Enforce Constrained Language Mode (CLM) to limit PowerShell functionality to basic features.", priority="High", effort="Medium"),
        MitigationStep(title="PowerShell Script Block Logging", description="Enable PowerShell Script Block Logging (Event ID 4104) to capture the full content of executed scripts.", priority="High", effort="Low"),
        MitigationStep(title="Disable Unused PowerShell Versions", description="Uninstall or disable PowerShell v2 to prevent attackers from bypassing modern logging.", priority="Medium", effort="Low")
    ],
    'T1547.001': [
        MitigationStep(title="Monitor Registry Run Keys", description="Implement monitoring for changes to common persistence keys in HKLM and HKCU (Run, RunOnce).", priority="High", effort="Low"),
        MitigationStep(title="Application Execution Prevention", description="Use AppLocker or Windows Defender Application Control to prevent execution from suspicious paths.", priority="High", effort="Medium")
    ],
    'T1548': [
        MitigationStep(title="UAC Enforcement", description="Ensure User Account Control (UAC) is enabled and set to 'Always Notify' for all accounts.", priority="High", effort="Low"),
        MitigationStep(title="Restrict Local Admin", description="Remove users from the local Administrators group and use Just-In-Time (JIT) access instead.", priority="High", effort="Medium")
    ]
}

DEFAULT_MITIGATIONS = [
    MitigationStep(title="Enable Comprehensive Logging", description="Ensure all systems ship logs to a centralized SIEM for correlation and threat detection.", priority="High", effort="Medium"),
    MitigationStep(title="Network Traffic Analysis", description="Deploy NTA/NDR solution to detect anomalous network behavior and C2 communications.", priority="High", effort="High"),
    MitigationStep(title="Vulnerability Management", description="Run regular vulnerability scans and prioritize patching using CVSS scores.", priority="Medium", effort="Medium"),
    MitigationStep(title="Incident Response Plan", description="Develop and regularly test an incident response playbook for rapid containment.", priority="High", effort="Low")
]


def calculate_confidence(text: str, signature_keywords: list) -> float:
    """Calculate confidence score based on keyword density.
    Uses word-boundary matching to prevent substring false positives.
    Favors multi-word phrases for higher precision.
    """
    text_lower = text.lower()
    matches = 0
    phrase_matches = 0
    has_technical_single_word = False
    
    for kw in signature_keywords:
        kw_low = kw.lower()
        if ' ' in kw_low:
            if kw_low in text_lower:
                phrase_matches += 1
                matches += 1
        else:
            import re
            if re.search(r'\b' + re.escape(kw_low) + r'\b', text_lower):
                matches += 1
                if kw_low not in _GENERIC_STOPWORDS:
                    has_technical_single_word = True
                
    if matches < 1:
        return 0.0
    
    # Scale based on 2 highly specific matches maxing out the heuristic confidence
    # Give a small bonus for specific multi-word phrases
    base = 0.5 + (matches / 2.0) * 0.45
    if phrase_matches > 0:
        base += 0.05
        
    confidence = min(0.95, base)
    
    # Precision boost for exact matches
    if phrase_matches > 0:
        # Multi-word phrases (e.g. "web shell", "sql injection") ALWAYS get top boost mapping regardless of text length
        confidence = max(confidence, 0.98)
    elif matches >= 1 and len(text) < 50:
        # For single words in short texts, boost if technical (e.g. "webshell", "mimikatz")
        boost = 0.98 if has_technical_single_word else 0.82
        confidence = max(confidence, boost)
        
    return confidence


def classify_threats(processed_input: Dict[str, Any]) -> Dict[str, float]:
    """Classify threat types from processed input and return their base confidence."""
    text = processed_input.get('normalized_text', '')
    detected = {}
    
    # 1. Use pre-suggested techniques from input processor
    for tech_id in processed_input.get('suggested_techniques', []):
        detected[tech_id] = 0.90

    # 2. Stage 1 Nano Pipeline: SecBERT Classification (Deep Learning TRAM)
    from core.secbert_classifier import secbert_clf
    
    # Try SecBERT first
    ml_predictions = secbert_clf.predict_techniques(text)
    
    if ml_predictions:
        for tech_id, conf in ml_predictions.items():
            detected[tech_id] = conf
            
    # 3. Apply Heuristic signature detection (HIGHER PRIORITY for precision on short strings)
    heuristic_matched = False
    for threat_type, sig in THREAT_SIGNATURES.items():
        base_confidence = calculate_confidence(text, sig['keywords'])
        if base_confidence > 0.58: # Balanced heuristic threshold
            heuristic_matched = True
            for i, t in enumerate(sig['techniques']):
                # Heuristics can OVERWRITE ML if confidence is higher (precision boost)
                # Apply positional decay: 1st technique gets full boost, subsequent drop by 3%
                decayed_conf = max(0.60, base_confidence - (i * 0.03))
                if t not in detected or decayed_conf > detected[t]:
                    detected[t] = decayed_conf

    # NEW: If we found a direct high-precision heuristic match for a very short string, 
    # suppress unrelated ML "contextual noise" to keep mapping localized.
    if heuristic_matched and len(text) < 50:
        # For very short strings, we ONLY trust the direct heuristic matches 
        # if they have significantly higher or equal confidence.
        top_conf = max(detected.values()) if detected else 0
        detected = {k: v for k, v in detected.items() if v >= top_conf - 0.005}

    return detected


def determine_severity(text: str, technique_ids: List[str]) -> Tuple[SeverityLevel, float, float]:
    """Determine severity, likelihood, and impact scores by evaluating all risk factors and taking the maximum."""
    text_lower = text.lower()
    
    potential_scores = []

    # 1. Signature-based Granularity (SQLi, Credential Dumping, etc.)
    if 'sql injection' in text_lower:
        # Differentiate SQLi types
        if any(kw in text_lower for kw in ['union select', 'drop table', 'truncate', 'sleep(', 'benchmark(']):
            potential_scores.append((SeverityLevel.HIGH, 3.8, 4.5)) # Heavy SQLi
        else:
            potential_scores.append((SeverityLevel.MEDIUM, 2.8, 3.2)) # Standard probe

    if 'credential' in text_lower or 'password' in text_lower:
        if 'mimikatz' in text_lower or 'lsass' in text_lower:
             potential_scores.append((SeverityLevel.CRITICAL, 4.8, 5.0))
        else:
             potential_scores.append((SeverityLevel.HIGH, 3.5, 4.0))

    # 2. Check for other high-level severity indicators
    for severity, keywords in SEVERITY_KEYWORDS.items():
        if any(kw in text_lower for kw in keywords):
            if severity == SeverityLevel.CRITICAL:
                potential_scores.append((SeverityLevel.CRITICAL, 4.6, 5.0))
            elif severity == SeverityLevel.HIGH:
                potential_scores.append((SeverityLevel.HIGH, 3.6, 4.2))
            elif severity == SeverityLevel.MEDIUM:
                potential_scores.append((SeverityLevel.MEDIUM, 2.6, 3.2))
    
    # 3. Base severity on number of techniques detected
    num_techs = len(technique_ids)
    if num_techs >= 5:
        potential_scores.append((SeverityLevel.CRITICAL, 4.2, 4.8))
    elif num_techs >= 3:
        potential_scores.append((SeverityLevel.HIGH, 3.2, 3.8))
    elif num_techs >= 1:
        potential_scores.append((SeverityLevel.MEDIUM, 2.2, 2.8))
    else:
        potential_scores.append((SeverityLevel.LOW, 1.2, 1.5))

    # Determine the maximum score
    # Severity enum values are strings, so we rank them by the sum of likelihood + impact
    best_score = max(potential_scores, key=lambda x: x[1] + x[2], default=(SeverityLevel.LOW, 1.2, 1.5))
    return best_score


def get_attack_techniques(technique_scores: Dict[str, float], text: str) -> List[ATTACKTechnique]:
    """Get full technique objects with real semantic confidence scores."""
    technique_ids = list(technique_scores.keys())
    techniques = []
    seen = set()

    # Batch-compute real cosine similarity scores for all technique IDs at once
    semantic_scores = technique_embedder.batch_score_techniques(text, technique_ids)


    for technique in _ATTACK_DB:
        if technique['id'] in technique_ids and technique['id'] not in seen:
            seen.add(technique['id'])

            # ML or Heuristic base confidence
            base_conf = technique_scores.get(technique['id'], 0.5)
            # Semantic contextual match confidence
            semantic_conf = semantic_scores.get(technique['id'], 0.5)

            # Smart confidence blending
            if base_conf >= 0.80:
                # If we have a very high-precision match (ML or Heuristic), trust it.
                # Don't let low semantic similarity for short strings pull down our decayed heuristic pipeline.
                confidence = max(base_conf, semantic_conf)
            elif semantic_conf >= 0.45:
                # Strong semantic link: trust the base confidence or semantic link
                confidence = max(base_conf, semantic_conf)
                if confidence > 0.5:
                    confidence = min(0.99, confidence)
            else:
                # Weak semantic link: likely just context or a co-occurrence ML prediction
                # We pull it down to visually separate it
                confidence = (base_conf * 0.7) + (semantic_conf * 0.3)

            confidence = round(confidence, 2)

            techniques.append(ATTACKTechnique(
                id=technique['id'],
                name=technique['name'],
                tactic=technique['tactic'],
                tactic_id=technique['tactic_id'],
                description=technique['description'],
                confidence=confidence
            ))

    sorted_techniques = sorted(techniques, key=lambda t: t.confidence, reverse=True)
    
    # Filter out low confidence speculative results. Since we boosted the blend, 
    # anything below 0.70 is likely noise for simple inputs.
    filtered_techniques = [t for t in sorted_techniques if t.confidence >= 0.70]
    
    # Dynamically cap the results based on confidence tiers and input density
    final_techniques = []
    text_len = len(text)
    
    # Define a strict total cap for very short logs to prevent noise over-mapping
    # Standard logs (e.g. 1-2 lines) usually shouldn't have more than 2-3 techniques.
    total_cap = 3 if text_len < 120 else 25
    
    tier_2_count = 0
    tier_3_count = 0

    for t in filtered_techniques:
        if len(final_techniques) >= total_cap:
            break
            
        if t.confidence >= 0.80:
            # Include all high confidence techniques (including our new decayed heuristics)
            final_techniques.append(t)  
        elif t.confidence >= 0.75:
            # Include medium-high confidence techniques
            # Cap at 3 for short inputs (<150 chars), or 6 for standard ones
            tier_cap = 3 if text_len < 150 else 6
            if tier_2_count < tier_cap:
                final_techniques.append(t)
                tier_2_count += 1
        else:
            # Include standard confidence techniques (0.70 - 0.74)
            # Cap at 1 for short entries, or 4 for standard ones
            tier_cap = 1 if text_len < 150 else 4
            if tier_3_count < tier_cap:
                final_techniques.append(t)
                tier_3_count += 1
                
    return final_techniques


def get_mitigations(technique_ids: List[str]) -> List[MitigationStep]:
    """Get mitigation steps for detected techniques."""
    mitigations = []
    seen_titles = set()
    
    for tech_id in technique_ids[:5]:  # Top 5 techniques
        if tech_id in TACTICAL_MITIGATIONS:
            for m in TACTICAL_MITIGATIONS[tech_id]:
                if m.title not in seen_titles:
                    seen_titles.add(m.title)
                    mitigations.append(m)
    
    # Add defaults if we don't have enough
    for m in DEFAULT_MITIGATIONS:
        if m.title not in seen_titles and len(mitigations) < 8:
            seen_titles.add(m.title)
            mitigations.append(m)
    
    return mitigations[:6]


def generate_business_impact(severity: SeverityLevel, technique_ids: List[str]) -> str:
    """Generate business impact narrative."""
    impacts = {
        SeverityLevel.CRITICAL: "Severe business disruption risk. Potential for complete system compromise, significant data breach, financial loss, and regulatory penalties. Immediate executive escalation required.",
        SeverityLevel.HIGH: "Significant business risk. Could lead to data exposure, service disruption, and reputational damage. Executive notification and emergency response required.",
        SeverityLevel.MEDIUM: "Moderate business impact. Contains risk of limited data exposure or service degradation. Prompt remediation required within 72 hours.",
        SeverityLevel.LOW: "Low business impact. Represents reconnaissance or early-stage threat activity. Monitor closely and remediate within SLA."
    }
    
    # Add technique-specific context
    if 'T1486' in technique_ids:
        return "RANSOMWARE RISK: " + impacts.get(severity, "Unknown impact")
    if 'T1048' in technique_ids or 'T1041' in technique_ids:
        return "DATA EXFILTRATION RISK: " + impacts.get(severity, "Unknown impact")
    
    return impacts.get(severity, "Unknown business impact")


# Technique → human-readable tactic stage labels
_TACTIC_STAGE = {
    'T1190': 'Initial Access via Vulnerability Exploitation',
    'T1566': 'Spear-Phishing / Initial Access',
    'T1059': 'Execution via Scripting Interpreter',
    'T1059.001': 'PowerShell-Based Execution',
    'T1053': 'Scheduled Task Persistence',
    'T1055': 'Process Injection',
    'T1003': 'Credential Dumping (LSASS / SAM)',
    'T1078': 'Valid Account Abuse',
    'T1110': 'Brute Force / Password Attack',
    'T1021': 'Lateral Movement via Remote Services',
    'T1080': 'Lateral Movement via Shared Content',
    'T1071': 'C2 via Application Layer Protocol',
    'T1095': 'C2 via Non-Application Layer Protocol',
    'T1048': 'Exfiltration over Alternative Protocol',
    'T1041': 'Exfiltration over C2 Channel',
    'T1486': 'Data Encryption for Impact (Ransomware)',
    'T1485': 'Data Destruction',
    'T1560': 'Data Archiving for Exfiltration',
    'T1548': 'Privilege Escalation via Abuse of Mechanism',
    'T1134': 'Privilege Escalation via Token Impersonation',
    'T1068': 'Exploitation for Privilege Escalation',
    'T1547': 'Boot/Logon Autostart Persistence',
    'T1543': 'System Service Persistence',
    'T1046': 'Network Service Discovery/Scanning',
    'T1040': 'Network Sniffing/Traffic Interception',
    'T1558': 'Kerberos Ticket Theft',
    'T1555': 'Credential Access from Password Stores',
    'T1570': 'Lateral Tool Transfer',
    'T1489': 'Service Stop / Disruptive Impact',
}

# Priority ordering: later kill-chain stages first in title selection
_TITLE_PRIORITY = [
    ('T1486', 'Ransomware Attack'), ('T1485', 'Data Destruction Attack'),
    ('T1048', 'Data Exfiltration via DNS/Alternative Channel'),
    ('T1041', 'Data Exfiltration via C2 Channel'),
    ('T1560', 'Data Staging and Exfiltration'),
    ('T1003', 'Credential Dumping Attack'), ('T1558', 'Kerberos Credential Theft'),
    ('T1078', 'Compromised Credential Abuse'),
    ('T1021', 'Lateral Movement Attack'), ('T1080', 'Internal Network Lateral Movement'),
    ('T1071', 'Covert C2 Communication'), ('T1095', 'Covert C2 Communication'),
    ('T1055', 'Process Injection / Defense Evasion'),
    ('T1068', 'Local Privilege Escalation'),
    ('T1548', 'Privilege Escalation'),
    ('T1059', 'Malicious Script Execution'), ('T1059.001', 'PowerShell Attack'),
    ('T1053', 'Scheduled Task / Persistence Mechanism'),
    ('T1566', 'Phishing Campaign'), ('T1190', 'Vulnerability Exploitation'),
    ('T1046', 'Network Reconnaissance'), ('T1040', 'Network Traffic Interception'),
    ('T1110', 'Brute Force Credential Attack'),
]


def _get_threat_title(technique_ids: List[str], entities: List[Any]) -> str:
    """Generate meaningful threat title based on highest-priority detected technique."""
    for tech_id, label in _TITLE_PRIORITY:
        if tech_id in technique_ids:
            return f"Detected: {label}"
    # Fallback: use the first technique's tactic if we have an attack DB
    if _ATTACK_DB and technique_ids:
        for tech in _ATTACK_DB:
            if tech['id'] == technique_ids[0]:
                return f"Detected: {tech['name']} — {tech['tactic']}"
    return "Detected: Multi-Stage Cyber Threat"


def _extract_entities(text: str) -> List[Dict[str, str]]:
    """
    Extract specific entities (tools, malware, CVEs, IPs, domains) using 
    both structured regex and spaCy NER (if available).
    Returns a unified list of entity dictionaries.
    """
    entities = []
    text_lower = text.lower()
    
    # 1. Regex-based extraction (high precision)
    cves = re.findall(r'CVE-\d{4}-\d{4,7}', text, re.IGNORECASE)
    for cve in set(cves):
        entities.append({'type': 'cve', 'value': cve.upper()})
        
    ips = re.findall(r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b', text)
    for ip in set(ips):
        entities.append({'type': 'ip', 'value': ip})
        
    hashes = re.findall(r'\b[a-fA-F0-9]{32,64}\b', text)
    for h in set(hashes):
        entities.append({'type': 'hash', 'value': h})

    domains = re.findall(r'\b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]\b', text_lower)
    for domain in set(domains):
        # Exclude common false positives
        if domain not in ('exe', 'dll', 'com', 'bat', 'sh', 'txt') and len(domain) > 4:
             if domain not in [e['value'] for e in entities if e['type'] == 'ip']:
                 entities.append({'type': 'domain', 'value': domain})

    # 2. Known Dictionary extraction (high precision)
    known_tools = [
        'mimikatz', 'cobalt strike', 'metasploit', 'cobaltstrike',
        'meterpreter', 'beacon', 'bloodhound', 'sharphound', 'impacket',
        'psexec', 'powershell', 'wmiexec', 'crackmapexec', 'empire',
        'emotet', 'ryuk', 'lockbit', 'conti', 'blackcat', 'alphv',
        'wannacry', 'petya', 'notpetya', 'darkside', 'revil', 'sodinokibi',
        'lazarus', 'apt28', 'apt29', 'apt41', 'fin7', 'carbanak',
        '7-zip', '7zip', 'winrar', 'certutil', 'bitsadmin', 'regsvr32',
        'mshta', 'wscript', 'cscript', 'rundll32', 'schtasks', 'at.exe',
        'nltest', 'secretsdump', 'procdump', 'nmap', 'sqlmap', 'burpsuite'
    ]
    for t in known_tools:
        if t in text_lower:
            entities.append({'type': 'tool', 'value': t})

    # 3. spaCy NER (extracts proper nouns we might have missed)
    if _nlp:
        doc = _nlp(text)
        for ent in doc.ents:
            # We are interested in Organizations (often malware/groups), Products, and Persons
            if ent.label_ in ['ORG', 'PRODUCT', 'PERSON']:
                val = ent.text.strip()
                # Exclude if it's already in our dictionary or regex hits
                val_lower = val.lower()
                if len(val) > 2 and not any(val_lower in e['value'].lower() for e in entities) and val_lower not in known_tools:
                    # Generic filter
                    if val_lower not in ['microsoft', 'windows', 'linux', 'apple', 'google', 'aws']:
                        entities.append({'type': 'organization/product', 'value': val})
    
    # Deduplicate while preserving order
    seen = set()
    unique_entities = []
    for e in entities:
        # Create a lowercase hashable key
        k = f"{e['type']}:{e['value'].lower()}"
        if k not in seen:
            seen.add(k)
            unique_entities.append(e)
            
    return unique_entities


def generate_predictive_actions(technique_ids: List[str], text: str = '', entities: List[Any] = None) -> List[PredictedStep]:
    """
    Generate DYNAMIC predicted steps based on the SPECIFIC techniques,
    tools, and CVEs detected.
    """
    if entities is None:
        entities = []
    if not technique_ids:
        return []

    # Extract comprehensive entities using NER and regex
    extracted_entities = _extract_entities(text)
    
    detected_tools = [e['value'] for e in extracted_entities if e['type'] == 'tool']
    detected_cves = [e['value'] for e in extracted_entities if e['type'] == 'cve']
    
    # Pre-populate input entities with our extractions so they show up in the UI
    for ext_e in extracted_entities:
        if not any((e.value if isinstance(e, ThreatEntity) else e.get('value', '')).lower() == ext_e['value'].lower() for e in entities):
            try:
                # Add as ThreatEntity schema-compatible instance
                entities.append(ThreatEntity(
                    type=ext_e['type'],
                    value=ext_e['value'],
                    context='NLP Extracted'
                ))
            except Exception:
                pass
    
    steps = []
    step_id = 1

    # Next-step prediction based on kill-chain position
    has_initial_access = any(t in technique_ids for t in ['T1190', 'T1566', 'T1133', 'T1091'])
    has_execution = any(t in technique_ids for t in ['T1059', 'T1059.001', 'T1053', 'T1055'])
    has_cred_access = any(t in technique_ids for t in ['T1003', 'T1110', 'T1078', 'T1555', 'T1558'])
    has_lateral = any(t in technique_ids for t in ['T1021', 'T1080', 'T1570'])
    has_c2 = any(t in technique_ids for t in ['T1071', 'T1095', 'T1048', 'T1041'])
    has_impact = any(t in technique_ids for t in ['T1486', 'T1485', 'T1489'])
    has_exfil = any(t in technique_ids for t in ['T1041', 'T1048', 'T1560', 'T1005'])

    if has_impact or has_exfil:
        steps.append(PredictedStep(
            id=step_id,
            title="Final Objective Containment",
            description="The attacker has reached the final objective phase. Ransomware encryption or data exfiltration is likely active. Immediately isolate affected hosts and revoke domain credentials.",
            confidence=0.95
        ))
        step_id += 1
    elif has_lateral and has_cred_access:
        loc = 'via RDP, SMB, or WMI' if 'T1021' in technique_ids else 'across internal systems'
        steps.append(PredictedStep(
            id=step_id,
            title="Internal Lateral Movement",
            description=f"The attacker is conducting lateral movement {loc} using stolen credentials. Expect immediate targeting of domain controllers and backup servers.",
            confidence=0.9
        ))
        step_id += 1
    elif has_cred_access:
        steps.append(PredictedStep(
            id=step_id,
            title="Privilege Escalation & Lateral Spread",
            description="The attacker has obtained credentials. Expect attempts to escalate privileges to Domain Admin or Move Laterally across the network using Pass-the-Hash/Ticket.",
            confidence=0.85
        ))
        step_id += 1
    elif has_initial_access or has_execution:
        steps.append(PredictedStep(
            id=step_id,
            title="Discovery & Persistence",
            description="Initial access established. Expect local system discovery (whoami, net view) and persistence mechanism installation (scheduled tasks, registry run keys).",
            confidence=0.8
        ))
        step_id += 1
    else:
        steps.append(PredictedStep(
            id=step_id,
            title="Further Exploration & Foothold",
            description="The attacker is in an early-stage reconnaissance or execution phase. Monitor for escalating activity: unusual process spawning or outbound connections.",
            confidence=0.7
        ))
        step_id += 1

    return steps



def analyze_threat(processed_input: Dict[str, Any], deep_analysis: bool = False) -> ThreatResult:
    """
    Main industrial-grade threat analysis function.
    Orchestrates the two-stage AI pipeline (SecBERT + Phi-3.5) with heuristic baselines.
    """
    text = processed_input.get('normalized_text', '')
    entities = processed_input.get('entities', [])

    # 1. Heuristic Baseline Scoring (Fast)
    technique_scores = classify_threats(processed_input)
    # determine_severity returns (severity, likelihood, impact) as enums/floats
    severity, likelihood, impact = determine_severity(text, list(technique_scores.keys()))
    
    # Calculate initial CVSS-inspired score (0-10)
    base_score = float(round((likelihood * 0.4 + impact * 0.6) * 2, 1))
    base_score = min(10.0, base_score)

    # 2. Industrial ML Ensemble (SecBERT + Phi-3.5)
    # evaluate_threat performs Stage 1 (TTP mapping) and Stage 2 (LLM reasoning)
    is_anomalous, final_score, deep_insights = ml_engine.evaluate_threat(processed_input, base_score, deep_analysis=deep_analysis)
    
    # 3. Dynamic Variance (Prevent "Clumping" at identical values like 6.6)
    # Add minor deterministic shift (+/- 0.3) based on text length and entity density
    if final_score is not None:
        text_factor = (len(text) % 100) / 200.0 # 0.0 to 0.5
        entity_factor = (len(entities) % 10) / 20.0 # 0.0 to 0.5
        # deterministic "jitter" so identical types but different payloads have different scores
        variance = (text_factor + entity_factor) - 0.5 
        final_score = float(np.clip(final_score + variance, 0.0, 10.0))
        final_score = round(final_score, 1)
    
    # 3. Final Result Construction
    final_techniques_list = []
    if deep_analysis and deep_insights:
        # TTPs from ML Engine Stage 3 already contain name, confirmed ID, and verified status
        # but LLM-detected ones might just be strings
        raw_ttps = deep_insights.get("ttps", [])
        
        # Normalize: convert all to dicts and deduplicate
        normalized_ttps = []
        seen_tids = set()
        
        for ttp in raw_ttps:
            if isinstance(ttp, str):
                tid = ttp
                ttp_dict = {"id": tid, "name": "Classified Technique", "confidence": 0.85, "verified": False, "evidence": ["AI Reasoning"]}
            else:
                tid = ttp.get("id")
                ttp_dict = ttp
                
            if tid and tid not in seen_tids:
                seen_tids.add(tid)
                normalized_ttps.append(ttp_dict)

        for ttp in normalized_ttps:
            tid = ttp.get("id")
            # Hydrate name/tactic from DB if it's the placeholder or missing
            name = ttp.get("name")
            tactic = ttp.get("tactic", "Multiple Tactics")
            
            if (not name or name == "Classified Technique") and tid in _ATTACK_LOOKUP:
                name = _ATTACK_LOOKUP[tid].get("name", name)
                tactic = _ATTACK_LOOKUP[tid].get("tactic", tactic)

            # Propagate "Verified" status and evidence to the final result
            final_techniques_list.append(ATTACKTechnique(
                id=tid,
                name=name or "Classified Technique",
                tactic=tactic,
                confidence=float(round(ttp.get("confidence", 0.5), 2)),
                verified=ttp.get("verified", False),
                evidence=ttp.get("evidence", [])
            ))
    
    if not final_techniques_list: # Fallback if deep_analysis didn't yield TTPs or wasn't enabled
        final_techniques_list = get_attack_techniques(technique_scores, text)

    # Map score to standard SeverityLevel
    mapped_severity = SeverityLevel.LOW
    if final_score >= 9.0: mapped_severity = SeverityLevel.CRITICAL
    elif final_score >= 7.0: mapped_severity = SeverityLevel.HIGH
    elif final_score >= 4.0: mapped_severity = SeverityLevel.MEDIUM

    # 4. Mitigation & Prediction Generation
    final_tids = [t.id for t in final_techniques_list]
    
    # Generate predictive steps
    # A) Deterministic steps from heuristics
    deterministic_steps = generate_predictive_actions(final_tids, text, entities)
    
    # B) AI-generated steps from Llama 3
    ai_steps_raw = deep_insights.get("predicted_steps", [])
    ai_steps = []
    
    # Start ID after deterministic ones
    next_id = len(deterministic_steps) + 1
    for step in ai_steps_raw:
        if isinstance(step, dict) and 'title' in step and 'description' in step:
            ai_steps.append(PredictedStep(
                id=next_id,
                title=step['title'],
                description=step['description'],
                confidence=float(step.get('confidence', 0.8))
            ))
            next_id += 1
            
    # Combine both
    final_predicted_steps = deterministic_steps + ai_steps

    result = ThreatResult(
        id=str(uuid.uuid4()),
        title=deep_insights.get("title") if deep_insights and deep_insights.get("title") != "Threat Detected" else _get_threat_title(final_tids, entities),
        timestamp=datetime.now().isoformat(),
        input_type=processed_input.get('input_type', 'text'),
        description=deep_insights.get("analysis", text[:300]) if deep_insights else text[:300],
        risk_score=RiskScore(
            score=float(round(final_score, 1)),
            severity=mapped_severity,
            likelihood=float(likelihood) if not is_anomalous else 0.8,
            impact=float(impact),
            business_impact=generate_business_impact(mapped_severity, final_tids)
        ),
        attack_techniques=final_techniques_list,
        defend_countermeasures=map_to_defend(final_tids),
        nist_controls=map_to_nist(final_tids),
        owasp_items=map_to_owasp(final_tids),
        mitigations=get_mitigations(final_tids),
        predicted_steps=final_predicted_steps,
        entities=[(e if isinstance(e, ThreatEntity) else ThreatEntity(type=e.get('type', 'indicator'), value=e.get('value', ''))) for e in entities],
        raw_indicators={
            "technique_ids": final_tids,
            "is_anomaly": bool(is_anomalous),
            "deep_extraction": deep_insights.get("terms", []),
            "technical_dive": deep_insights.get("analysis", ""),
            "llm_summary": deep_insights.get("summary", "")
        }
    )
    return result
